[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate && gunicorn fakturex.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
